import { launch } from './_launch.mjs';
const out = process.env.OUT || '/tmp'; const PORT = process.env.PORT || '5173';
const b = await launch();
const p = await b.newPage({ viewport: { width: 1000, height: 800 } });
p.on('console', m => { const t=m.text(); if(!t.includes('[vite]')) console.log('PAGE:', t); });
p.on('pageerror', e => console.log('PAGEERR:', e.message));
await p.goto(`http://127.0.0.1:${PORT}/terra.html`, { waitUntil: 'load' });
await p.waitForTimeout(4000);
console.log('world:', await p.evaluate(() => window.__terra?.world_name?.() ?? 'none'));
await p.screenshot({ path: `${out}/terra-globe.png` });
await b.close(); console.log('done');
